# frontend/Dockerfile
FROM python:3.9
WORKDIR /app
COPY ML_demo_frontend.py /app/
RUN pip install streamlit requests pillow
EXPOSE 8501
CMD ["streamlit", "run", "ML_demo_frontend.py", "--server.port=8501", "--server.address=0.0.0.0"]
